INSERT INTO Items (desc_item, marca_item) VALUES
('Chocolate ao Leite', 'Hershey''s'),
('Achocolatado em Pó Nescau', 'Nestlé'),
('Leite Integral', 'Italac'),
('Leite Condensado', 'Piracanjuba'),
('Farinha de Trigo', 'Dona Benta'),
('Creme de Leite', 'Frimesa'),
('Fermento em Pó', 'Royal'),
('Açúcar Cristal', 'União'),
('Sal Marinho', 'Lebre'),
('Bicarbonato de Sódio', 'Kitano'),
('Creme de Leite', 'Itambé'),
('Essência de Baunilha', 'Dr.Oetker'),
('Pasta Americana', 'Pasta Americana'),
('Confeito', 'Dori'),
('Chocolate Amargo', 'Talento'),
('Cream Cheese', 'Philadelphia'),
('Manteiga com Sal', 'Aviação'),
('Ovo', 'Granja');
